### ISSUE TITLE
Not working on iOS with Fastclick.js

### ISSUE THREAD

**Issue by allaire** [dbushell/Pikaday#101]
Version on your demo is working well on iOS, but the current master version and even the version or your demo is not working in our app.

I got it to work by using

``` javascript
        addEvent(self.el, 'mousedown', self._onMouseDown, true);
        addEvent(self.el, 'touchstart', self._onMouseDown, true); // Fix for iOS
```

**EDIT**

Looks like it's related to Fastclick.js:

https://github.com/ftlabs/fastclick/pull/103

**Comment by nayaabkhan** [comment]
@basicallydan +1. I am facing the same issue, and we use pikaday as a commons module with Browserify. So everyone working on the team would need to change the source after installing pikaday through npm, which is not the best option I think.

It would be great to see the solution in the next version.

**Comment by schoenkaft** [comment]
Although this issue is closed, I would suggest to change the suggested  `touchstart` to `touchend`. It will still trigger on iOS 8, but won't trigger anything after the datepicker closes. When using `touchstart`, any `touchend` trigger will still fire.

It doesn't matter if the datepicker is positioned `absolute` or `relative`, in my experience `touchstart` will still fire `touchend` on any object that appears beneath the `touchstart` after you've selected (and in most cases closed) Pikaday. Any thoughts?

In my case I have the datepicker positioned relative, but after picking a date it will still select and execute any `<a>` that will 'move up' when the `relative` datepicker disappears. In my opinion `touchend` would be a saver bet.

So: `addEvent(self.el, 'touchend', self._onMouseDown, true); // Fix for iOS`

**Comment by schoenkaft** [comment]
Sidenote: it appears that on Chrome 40 (current stable) on Android 4.x and 5.0.x the event might still fire, but less often than with `touchstart`.

Preventing any event firing after the select will require:

 `e.preventDefault()` added to `self._onMouseDown = function(e)` (in `Pikaday = function(options)`)

As far as I can tell that should be pretty standard, because `_onMouseDown` should handle all user input on that point. It definitely should prevent any other unwanted events firing as far as I can tell, but this is of course based on empirical evidence, so please correct if I'm wrong.
