### ISSUE TITLE
SASS/SCSS version of style

### ISSUE THREAD

**Issue by theghostbel** [dbushell/Pikaday#130]
What do you think about adding scss version of pikaday.css? It has a lot of pros, one is we could easily change route picker class name and in overall rules could become easier to maintain

**Comment by thomasthesecond** [comment]
I've just done this on a project I'm currently working on. I could make a pull request. I imagine the SCSS version wouldn't replace the CSS version.

**Comment by espellcaste** [comment]
Awesmome @thomasthesecond !

**Comment by thomasthesecond** [comment]
Great. I've made the updates, I just need to test before I make the PR.

**Comment by rikkert** [comment]
Ideally it should be the source of the CSS, right?

**Comment by thomasthesecond** [comment]
You mean the SCSS should be the source of the CSS? What I've done for myself is just convert the CSS code to SCSS in order to leverage nesting and include it as a partial in my project. I guess the reason for the PR is to include the SCSS as an option for others to use it. But I can see the issue of having the styles in two locations; not very DRY.

**Comment by thomasthesecond** [comment]
Or maybe I'm not fully understanding the original intent of this issue.

**Comment by espellcaste** [comment]
@thomasthesecond I think that's exactly the original intent. Provide a sass version as another option.

**Comment by rikkert** [comment]
I do want to make it the source of the production CSS.

**Comment by thomasthesecond** [comment]
https://github.com/dbushell/Pikaday/pull/259
