### ISSUE TITLE
Setting date programatically failes

### ISSUE THREAD

**Issue by christophgasser** [dbushell/Pikaday#131]
I have two pikaday pickers on one site. They have different class/id. When changing the date of the first picker I want to update the date from the second picker programatically.
Therefore I thought it's best to use "onClose" event of the first picker. So when the first picker is closing, the second picker is updated.

Pickers have been working fine until I extended / added the "onClose" event for picker one.

This is my code for the "onClose" event:
START
onClose: function() {
            var departureDateInit = new Date();
            var arrivalDateNew = new Date();
            arrivalDateNew = Date.parse(document.getElementById('arrival').value);
            departureDateInit.setDate(arrivalDateNew.getDate() + 3);
            console.log("new departure date: " + departureDateInit);
            var departurePicker = new Pikaday({ field: $j('#departure')[0] });  
            departurePicker.setDate(departureDateInit);
END

The error I get is: Uncaught range exception. Maximum call stack size exceeded. This happens on line 70 from pikaday.js (current version).

I played arround now for a while and could not get that solved. I'm not sure if it is a bug or if I made something wrong. But as fas as I can say, the code should be fine.

**Comment by RobertMenke** [comment]
Has there been any follow up on this issue? I'm having the same problem over 2 years later.

**Comment by rikkert** [comment]
I meant something like this:
https://jsfiddle.net/7oggh0pr/
Is that what you guys mean?

**Comment by matfish2** [comment]
Having the same issue trying to build a wrapper for vue. 
My secenario is:
A. View->Model: `onSelect` I emit an `input` event to update vue's model
B. Model->View: I've set a watcher using `setDate` to update the UI when the model changes.

The problem seems to be that `setDate` triggers `onSelect`, which causes an infinite loop, eventually crashing the browser. If `setDate` is dissociated from `onSelect` the it seems the problem would be solved.
