### ISSUE TITLE
Prevent unwanted change event when page loads

### ISSUE THREAD

**Issue by asumaran** [dbushell/Pikaday#149]
I have a form with a pre-populated date input which i'm listen the change event to fetch results via ajax.

Happens every time the page is loaded the date input triggers the change event, which makes an unnecesary ajax request because the page is loading with results already.

Is there any way to avoid or silence the event only when the page just finished to load?

I'm wondering this because the prepopulated value is '21/05/2014' and the value after the change event remains '21/05/2014'

This is the code i'm using to configure Pikaday

``` javascript
$(function(){
  var picker = new Pikaday({
    field: document.getElementById('date'),
    format: "DD/MM/YYYY"
  });
});
```

**Comment by shyamchandranmec** [comment]
Any solution to this?

**Comment by Niarike** [comment]
I was able to fix this without putting the initialization in the HTML by editing the pikaday.js file on line 730 where there's a fireEvent call...I wrapped it with an if statement checking to see if 'preventOnSelect' was true because the initialization case was the only one I could find where true was sent in rather than null/false.  Code (with a few surrounding lines for clarity) looks like this:

728:  if(this._o.field) {
729:      this._o.field.value = this.toString();
730:      if (!preventOnSelect) {
731:            fireEvent(this._o.field, 'change', { firedBy: this });
732:      }
733:  }

**Comment by Yatekii** [comment]
Can you please reopen the issue and fix this?

I actually have a case where this behavior causes a stackoverflow as it will call the onchange event over and over again.
This is not really working with vdom libs (mithril in my case), I guess.

I don't see why the onchange event should be emitted when nothing actually changed.

Thanks a ton!

**Comment by bluebinary** [comment]
I had the same issue, and found that even the most recent version of Pikaday fires the `change` event on page load if the form field that is configured as a Pikaday field has a pre-populated date from previous user-input.

I found that by modifying `pikaday.js` on lines 852-854 (of the current committed file as of writing), to include an old/new value comparison around the `fireEvent()` call, that the `change` event now only fires when the data actually has changed.

Feel free to merge the changes referenced in the above forked commit to resolve Pikaday#149.
