### ISSUE TITLE
Attach to multiple inputs?

### ISSUE THREAD

**Issue by mgibbs189** [dbushell/Pikaday#2]
How do I attach Pikaday to multiple inputs?

E.g. a typical jQuery approach would look something like this:

```
$('.date-picker').pikaday();
```

**Comment by ronilaukkarinen** [comment]
I bashed my head with this for couple of hours and didn't get any of the examples to work... no errors in log, but no datepickers either.

Ended up just copying it like this:

```javascript
// Datepickers
    var startdate = new Pikaday({
      field: $('.reservation').find('#startdate')[0],
      format: 'DD/MM/YYYY',
      firstDay: 1
    });

    var enddate = new Pikaday({
      field: $('.reservation').find('#enddate')[0],
      format: 'DD/MM/YYYY',
      firstDay: 1
    });
```

**Comment by hugomelo** [comment]
Passing **$(this)** (jQuery object) doesn't work for me:
```js
var picker = [];
$('.date-picker').each(function(idx) {
    picker[idx] = new Pikaday({ field: $(this) });
});
```

 It only work when I  use only **this**. The direct element.

```js
var picker = [];
$('.date-picker').each(function(idx) {
    picker[idx] = new Pikaday({ field: this });
});
```

**Comment by giovanigenerali** [comment]
@hugomelo Try it:

**Comment by Dennniss** [comment]
Hello, i am using Ninja form, is there a way to select different dates in the Pickaday calendar in the same form field separeted with , for example?

**Comment by jtlindsey** [comment]
In some cases the `.each` and `$(this)` wasn't working for me. The alternative that worked was grabbing the element in the callback:

```
$('.datepicker').each(function(i, e) {
  new Pikaday({
    field: e,
    ...
  });
});
```

**Comment by chethan1095** [comment]
can we select only time using pikaday

**Comment by hugomelo** [comment]
@chethan1095, there's an explaination in the [README](https://github.com/dbushell/Pikaday#timepicker)

**Comment by gresbtim** [comment]
what's the no jquery equivalent?

**Comment by eLIANT-TechnologyServices** [comment]
On Mar 7, 2017, ronilaukkarinen said this method worked for him, but I'm getting nothin.  When I applied Pikaday to just one input, it worked fine.  But trying to apply to more than one produces no pop-up calendars on any of the input fields.

For context, it's an on-line job application form.

	var App = new Date();
	App.setDate(App.getDate() - 1);
	var pickerApp = new Pikaday({
      field: document.getElementById('Applied-before-date'),
      maxDate: App
    });

	var Emp = new Date();
	Emp.setDate(Emp.getDate() - 1);
	var pickerEmp = new Pikaday({
      field: document.getElementById('Employed-before-date'),
      maxDate: Emp
    });

	var bd = new Date();
	bd.setDate(bd.getDate() - 5479);
	var pickerBD = new Pikaday({
      field: document.getElementById('Birthdate'),
      maxDate: bd
	  defaultDate: bd

**Comment by milholen** [comment]
@eLIANT-TechnologyServices the working code examples above are compatible with jQuery syntax, your code examples are native JS. I don't think the non-jQuery version of Pikaday supports this. See issue #123 

Easiest solution: add jQuery to your project.

**Comment by eLIANT-TechnologyServices** [comment]
Thanks for your reply.

 

From your profile picture you don't appear to be a child, so maybe you can
appreciate what I'm about to say.

 

Dude, I'm tired of learning new languages.  I've gone through 14 different
programming, scripting, and report-writing languages in my carrier - since
before there were PCs.

 

I really do appreciate your response, but I just started with JS this year,
and I don't think I could make myself study hard enough to understand the
meaning of 

$('input.datep').pikaday({ firstDay: 1 });

 

From what I've seen, Pikaday has not been updated or supported officially
for a very long time.  Is there an alternative?

 

 

Sincerely, 
  
Philip W. Kelly 
eLIANT Technology Services 
  
 <http://www.eliantservices.com/> www.eliantservices.com 
937-974-5521

**Comment by gresbtim** [comment]
lmao. Philip, since this is my company account i can't flame you. 

but

`$('input.datep').pikaday({ firstDay: 1 });`



`$('input.datep')`  is usage of the jQuery library and returns a collection of elements. 

`.pikaday(` then calls the plugin "pikaday" for each of those elements and `{ firstDay: 1 }` are the parameters for pikaday

have a nice day.

**Comment by eLIANT-TechnologyServices** [comment]
Look at you – making me learn something new.

 

Okay, first things first… how do I “activate” JQ?  Like with JS I use <script>…</script>.  Do I do the same thing but just put JQ between <></>?

 

 

Sincerely, 
  
Philip W. Kelly 
eLIANT Technology Services 
  
 <http://www.eliantservices.com/> www.eliantservices.com 
937-974-5521

**Comment by gresbtim** [comment]
jquery is a library written in javascript
https://jquery.com/

you add the jquery source to your html site and then can use jquery functions within javascript code
