### ISSUE TITLE
Mixing jquery and native selectors

### ISSUE THREAD

**Issue by foxx** [dbushell/Pikaday#208]
Hello,

Even though pikaday can be used with jQuery, customizations still require getElementById, for example;

```
    $('.datepicker').pikaday({ 
      firstDay: 1,
      container: document.getElementById('pikaday-container'),
```

It would be nice if I could use a jquery selector instead.

**Comment by fernandofleury** [comment]
Well, technically speaking you can use the jQuery Selector still if you want. But then you would have to return the native JS object from it:

```javascript
container: $('#pikaday-container')[0]
```

The point of providing jQuery as a main wrapper for Pikaday works just fine because of referrence storage (you don't have to provide a variable for it), and allows easy query selecting for it.

But when we are talking about inner components, it's really not such of a big deal. I don't see a huge advantage on it, the code would bloat up in onder to support this.
