### ISSUE TITLE
require('../pikaday')) - why?

### ISSUE THREAD

**Issue by foxx** [dbushell/Pikaday#209]
Inside `jquery.pikaday.js` there is a line which has the following CommonJS wrapper;

```
    if (typeof exports === 'object') {
        // CommonJS module
        factory(require('jquery'), require('../pikaday'));
```

Why is this `../pikaday` instead of `pikaday`? This is the first time I've ever seen a module doing this, and it requires me to shim (or edit the source) to prevent it breaking our builds.

**Comment by rikkert** [comment]
Because in the package that is distributed the jQuery plugin is inside the directory plugins and pikaday is one directory higher so it requires it as ../pikaday(.js).
Not sure why it breaks in your build?

**Comment by dsnoeck** [comment]
Same issue for me.
@rikkert: Because when you concact and minify all your dependencies, pikaday is then in the same vendors.js file. This is the purpose of CommonJs: you declare (export) modules that you can require wherever you want.
On the exact same line, you require('jquery'). But jQuery is not in the same directory as your jquery.pikaday.js file !
