### ISSUE TITLE
Field on non input

### ISSUE THREAD

**Issue by AshotN** [dbushell/Pikaday#228]
Whenever I set the field to a non input it freeze's the browser.

This is my code so you can get an idea of what I'm doing (Coffeescript)

	$(".images").on 'click', '.date', ->
		picker = new Pikaday { field: $(this)[0]}

.date is an image

I have to use a delegate because the content is dynamically generated

If you can replicate the problem let me know, I'll create  a public page with it

**Comment by infacq** [comment]
+1

**Comment by SteveBash** [comment]
I've had a similar issue and I don't think it has to do with a non-input; is probably a "Maximum call stack size exceeded error", since you're attaching a new Pikaday for every click which also comes with a click event listener, a better solution perhaps is to instantiate a Pikaday outside the event delegation and append that to your field.
