### ISSUE TITLE
Allow function as 'format' parameter

### ISSUE THREAD

**Issue by rikschennink** [dbushell/Pikaday#266]
For handling custom formatting without momentjs?

**Comment by rahatarmanahmed** [comment]
+1

**Comment by rikkert** [comment]
Sorry you need momentjs for all formatting.

**Comment by rahatarmanahmed** [comment]
Moment js doesn't have the ability to create our own format function. My particular use case is to make a field display a date in a more user readable format like "Today, Tomorrow, In 2 Days" while still being able to access the raw date value.

I don't see why this can't be implemented in pikaday, because you can still use moment internally with a default format function depending on the provided format string. But if we pass a function it would use the output of that to display.
