### ISSUE TITLE
Close open pikaday on click on trigger?

### ISSUE THREAD

**Issue by nicmar** [dbushell/Pikaday#609]
I attach pikaday like this to a div/button, and not to an input field:
`$('.my-button').pikaday({ });`

So when I click the div, it pops up. But how can I make it close when I click the div again? I basically want to toggle it like a normal <select> would, since I've styled it to looked like a <select> with an arrow.

Thanks!

**Comment by NiallSmyth** [comment]
Pikaday isn't set up to work like that, clicking the bound field will always open the picker rather than toggling it, but you could make what you want work with a little more JS:

```
var picker = new Pikaday({field: $('.my-button')[0], bound: false});
var pickerOpen = false;
$('.my-button').click(function () {
    if (pickerOpen) {
        picker.hide(); 
    } else {
        picker.show();
    }
    pickerOpen = !pickerOpen;
});
```

Passing bound: false in the options prevents Pikaday from binding to the field's click event, so you can handle that yourself the way you want it to work.

**Comment by nicmar** [comment]
Thanks a lot, that was a smart and elegant solution!

**Comment by shenfusheng** [comment]
if I set bound: false，then pikaday can not show，why?
