### ISSUE TITLE
Left arrow on any other input is hijacked by Pikaday

### ISSUE THREAD

**Issue by markdavies** [dbushell/Pikaday#762]
This line here:
https://github.com/dbushell/Pikaday/blob/eddaaa3b26e2df84909d314789c0997db218b0bd/pikaday.js#L527

... will prevent the left arrow from being useful on any other text or textarea input.

**Comment by markdavies** [comment]
My bad, error at our end.

**Comment by JamoCA** [comment]
I just downloaded the latest version of Pikaday (1.6.1; 12/19/2017) from Github and line #527 hasn't been updated.  This issue is reported as "closed" but hasn't been "fixed".  Am I understanding this correctly?

It appears that 1.7.0 is available at another repository.  https://www.npmjs.com/package/pikaday  Is this correct?  Was this due to different ownership/collaboration?  Is there a major breaking change?  Will the source code be updated on Github too?
