### ISSUE TITLE
Keyboard Accessibility

### ISSUE THREAD

**Issue by dbushell** [dbushell/Pikaday#9]
To do.

**Comment by rikschennink** [comment]
If you want to do this without momentjs:

```javascript
var selectedDate = picker.getDate() || new Date();
var days = 0;

switch (keyCode) {
    case 33: // PageUp
        days = -365;
        break;
    case 34: // PageDown
        days = 365;
        break;
    case 35: // End
        days = -30;
        break;
    case 36: // Home
        days = 30;
        break;
    case 37: // Left
        days = -1;
        break;
    case 39: // Right
        days = 1;
        break;
    case 38: // Top
        days = -7;
        break;
    case 40: // Down
        days = 7;
        break;
    case 13: // Esc
    case 27: // Enter
        this._picker.hide();
        return;
}

picker.setDate(new Date(selectedDate.setDate(selectedDate.getDate() + days)));
```

**Comment by ryoia** [comment]
How do you make the calendar open on focus?

**Comment by dannylivewire** [comment]
This is awesome... has it been made into a PR yet?

**Comment by dannylivewire** [comment]
Did this not get made into a PR because it uses Moment.js & because the other solution didn't take into account Leap Year?

**Comment by kunal999** [comment]
I am not sure why this is still open. I think keyboard support was added in 1.5.1 by #522.

**Comment by jesserosenfield** [comment]
Does the Enter key just hide the calendar? 

Shouldn't the Enter key actually select the date that you've used the left/right arrows to hover over?

One thing I'm noticing is that if I want to add an event listener to the Enter Key in order to Submit the form once the date has been chosen– I believe that Pikaday's event listener is preventing that from happening.
